name/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'users#new'
  post '/sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/dashboard' => 'badname#index'
  get '/users' => 'users#index'

  resources :sudzibas do
      resources :piezimes
  end

	resources :clients

	 root 'welcome#index'
  get 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

name/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

name/app/models/client.rb
class Client < ApplicationRecord
  validates :vards, presence: { message: "ir obligati jaievada" }, length: { minimum: 3 }, format: { with: /\A[a-zA-Z]+\z/, message: "var saturet tikai burtus" }
  validates :uzvards, presence: { message: "ir obligati jaievada" }, length: { minimum: 3 }, format: { with: /\A[a-zA-Z]+\z/, message: "var saturet tikai burtus" }
  validates :tel_nummurs, presence: { message: "ir obligati jaievada" }, length: { in: 8..12 }
  validates :adrese, presence: { message: "ir obligati jaievada" }
end

name/app/models/piezime.rb
class Piezime < ApplicationRecord
  belongs_to :sudziba
    validates :commenter, presence: { message: "ir obligati jaievada" }, length:  {maximum: 30}
	validates :body, presence: { message: "ir obligati jaievada" }
end

name/app/models/sudziba.rb
class Sudziba < ApplicationRecord
	has_many :piezimes, dependent: :destroy
	validates :title, presence: { message: "ir obligati jaievada" }, length: { minimum: 5 } 
	validates :description, presence: { message: "ir obligati jaievada" } 
	validates :customer, presence: { message: "ir obligati jaievada" }, length:  {maximum: 30}
	validates :user, presence: { message: "ir obligati jaievada" }, length:  {maximum: 30}
	validates :status, presence: { message: "ir obligati jaievada" }, format: { with: /\A[a-zA-Z]+\z/, message: "var saturet tikai burtus" } 
end

name/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

name/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/' unless current_user
  end

end

name/app/controllers/badname_controller.rb
class BadnameController < ApplicationController
end

name/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
before_action :authorize
helper_method :sort_column, :sort_direction

def index
	@clients = Client.order(sort_column + " " + sort_direction)
end

def show
	@client = Client.find(params[:id])
end

def new
	@client = Client.new
end

def edit
	@client = Client.find(params[:id])
end

def create
  @client = Client.new(client_params)
 
  if @client.save
    redirect_to @client
  else
    render 'new'
  end
end

def update
  @client = Client.find(params[:id])
 
  if @client.update(client_params)
    redirect_to @client
  else
    render 'edit'
  end
end

def destroy
  @client = Client.find(params[:id])
  @client.destroy
 
  redirect_to clients_path
end

private
	def client_params
		params.require(:client).permit(:vards,:uzvards,:personas_kods,:tel_nummurs,:epasts,:adrese,:piezimes)
	end

  def sort_column
    Client.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

name/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

name/app/controllers/piezimes_controller.rb
class PiezimesController < ApplicationController

	def create
    	@sudziba = Sudziba.find(params[:sudziba_id])
    	@piezime = @sudziba.piezimes.create(piezime_params)
    	redirect_to sudziba_path(@sudziba)
	end
 
	def destroy
    	@sudziba = Sudziba.find(params[:sudziba_id])
    	@piezime = @sudziba.piezimes.find(params[:id])
    	@piezime.destroy
    	redirect_to sudziba_path(@sudziba)
  	end

private
    def piezime_params
    	params.require(:piezime).permit(:commenter, :body)
    end
end

name/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by(email:login_params[:email])
		if user && user.authenticate(login_params[:password])
			session[:user_id] = user.id 
			redirect_to '/sudzibas'
		else
			flash[:login_errors]=['Informacija nesakrit']
			redirect_to '/'
		end

	end

	private
	def login_params
		params.require(:login).permit(:email, :password)
	end
end

name/app/controllers/sudzibas_controller.rb
class SudzibasController < ApplicationController
before_action :authorize
helper_method :sort_column, :sort_direction	

  def index
    	@sudzibas = Sudziba.order(sort_column + " " + sort_direction )
  end

	def show
    	@sudziba = Sudziba.find(params[:id])
  end

	def new
		@sudziba = Sudziba.new
	end

	def edit
  		@sudziba = Sudziba.find(params[:id])
	end

	def create
		@sudziba = Sudziba.new(sudziba_params)
		 
 	    if @sudziba.save
    		redirect_to @sudziba
  		else
    		render 'new'
  		end
	end
	
	def update
  		@sudziba = Sudziba.find(params[:id])
 
  		if @sudziba.update(sudziba_params)
    		redirect_to @sudziba
  		else
    		render 'edit'
  		end
	end

  def destroy
    @sudziba = Sudziba.find(params[:id])
    @sudziba.destroy
 
    redirect_to sudzibas_path
  end

private
  def sudziba_params
    params.require(:sudziba).permit(:title, :description, :customer, :user, :status)
	end

  def sort_column
    Sudziba.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

name/app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "password", except: [:new, :show, :create]

	def index
		@users = User.all
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id 
			redirect_to '/sudzibas'
		else
			flash[:register_errors] = user.errors.full_messages
			redirect_to '/'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

name/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

name/app/helpers/application_helper.rb
module ApplicationHelper
end

name/app/helpers/badname_helper.rb
module BadnameHelper
end

name/app/helpers/clients_helper.rb
module ClientsHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, :sort => column, :direction => direction 
	end
end

name/app/helpers/pages_helper.rb
module PagesHelper
end

name/app/helpers/piezimes_helper.rb
module PiezimesHelper
end

name/app/helpers/sessions_helper.rb
module SessionsHelper
end

name/app/helpers/sudzibas_helper.rb
module SudzibasHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, :sort => column, :direction => direction
	end
end

name/app/helpers/users_helper.rb
module UsersHelper
end

name/app/helpers/welcome_helper.rb
module WelcomeHelper
end

name/app/views/clients/_form.html.erb
<%= form_with model: @client, local: true do |form| %>

  <% if @client.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@client.errors.count, "kluda") %> aizliedza sim klientam tikt izveidotam:
      </h4>
      <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">

  <p>
    <%= form.label :vards %><br>
    <%= form.text_field :vards %>
  </p>

  <p>
    <%= form.label :uzvards %><br>
    <%= form.text_field :uzvards %>
  </p>

  <p>
    <%= form.label :personas_kods %><br>
    <%= form.text_field :personas_kods %>
  </p>

  <p>
    <%= form.label :tel_nummurs %><br>
    <%= form.text_field :tel_nummurs %>
  </p>

  <p>
    <%= form.label :epasts %><br>
    <%= form.text_field :epasts %>
  </p>

  <p>
    <%= form.label :adrese %><br>
    <%= form.text_area :adrese %>
  </p>

  <p>
    <%= form.label :piezimes %><br>
    <%= form.text_area :piezimes %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

</div>
<% end %>

name/app/views/clients/edit.html.erb
<div class="container">
<div class="topright2"><%= current_user.email %></div>
<h3>Klienta info redigeshana</h3>
<hr />

<%= render 'form' %>

<%= link_to 'Atpakal', clients_path %>

</div>

name/app/views/clients/index.html.erb
<h3>Klientu saraksts</h3>
<%= link_to 'Jauns Klients', new_client_path %> |
<%= link_to 'Pieteikumu saraksts', sudzibas_path %> |
<%= link_to 'Lietotaju saraksts', users_path %> 
<div class="topright"><%= current_user.email %></div>

<table  class="table table-hover">
<thead>
  <tr>
    <th scope="col"><%= sortable "id" %></th>
    <th scope="col"><%= sortable "vards" %></th>
    <th scope="col"><%= sortable "uzvards" %></th>
    <th scope="col">Telefons</th>
    <th scope="col">E-pasts</th>
    <th scope="col"><%= sortable "adrese" %></th>
    <th scope="col" colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @clients.each do |client| %>
    <tr>
      <td><%= client.id %></td>
      <td><%= client.vards %></td>
      <td><%= client.uzvards %></td>
      <td><%= client.tel_nummurs %></td>
      <td><%= client.epasts %></td>
      <td><%= client.adrese %></td>
      <td><%= link_to 'Vairak', client_path(client) %></td>
      <td><%= link_to 'Rediget', edit_client_path(client) %></td>
      <td><%= link_to 'Dzest', client_path(client), method: :delete, data: { confirm: 'Vai jus esat parliecinati?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

name/app/views/clients/new.html.erb
<div class="container">
<div class="topright2"><%= current_user.email %></div>
<h3>Jauna Klienta lapa</h3>
<hr />

<%= render 'form' %>

<%= link_to 'Atcelt', clients_path %>

</div>

name/app/views/clients/show.html.erb
<div class="container">
<div class="topright2"><%= current_user.email %></div>
<h3>Klienta info</h3>
<hr />

  <strong>ID:</strong>
  <%= @client.id %> <br>

  <strong>Vards:</strong>
  <%= @client.vards %> <br>

  <strong>Uzvards:</strong>
  <%= @client.uzvards %> <br>

  <strong>Personas kods:</strong>
  <%= @client.personas_kods %> <br>

  <strong>Telefona nummurs:</strong>
  <%= @client.tel_nummurs %> <br>

  <strong>E-pasts:</strong>
  <%= @client.epasts %> <br>

  <strong>Adrese:</strong>
  <%= @client.adrese %> <br>

  <strong>piezimes:</strong>
  <%= @client.piezimes %> <br>

  <strong>Tika izveidots:</strong>
  <%= @client.created_at %> <br>

  <strong>Tika redigets:</strong>
  <%= @client.updated_at %> <br>
<hr />

<%= link_to 'Rediget', edit_client_path(@client) %> |
<%= link_to 'Atpakal', clients_path %> 

</div>

name/app/views/piezimes/_form.html.erb
<%= form_with(model: [ @sudziba, @sudziba.piezimes.build ], local: true) do |form| %>
  <p>
    <%= form.label :Komentetajs %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :Komentars %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

name/app/views/piezimes/_piezime.html.erb
<hr />
  <strong>Komentetajs:</strong>
  <%= piezime.commenter %> <br>
 
  <strong>Komentars:</strong>
  <%= piezime.body %> <br>
  
  <strong>Tika izveidots:</strong>
  <%= piezime.created_at %> <br>

  <%= link_to 'Dzest piezimi', [piezime.sudziba, piezime],
               method: :delete,
               data: { confirm: 'Vai jus esat parliecinati?' } %>

name/app/views/sudzibas/_form.html.erb
<%= form_with model: @sudziba, local: true do |form| %>
 
  <% if @sudziba.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h4>
        <%= pluralize(@sudziba.errors.count, "kluda") %> aizliedza sim pieteikumam tikt izveidotam:
      </h4>
      <ul>
        <% @sudziba.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="container">

  <p>
    <%= form.label :nosaukums %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :detalas %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :klients %><br>
    <%= form.text_field :customer %>
  </p>
 
  <p>
    <%= form.label :lietotajs %><br>
    <%= form.text_field :user %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.text_field :status %>
  </p>

  <p>
    <%= form.submit %>
  </p>
 
</div>

<% end %>

name/app/views/sudzibas/edit.html.erb
<div class="container">
<div class="topright2"><%= current_user.email %></div>

<h3>Rediget Pieteikumu</h3>
<hr />
 
<%= render 'form' %>

<%= link_to 'Atpakal', sudzibas_path %>

</div>

name/app/views/sudzibas/index.html.erb
<h3>Pieteikumu saraksts</h3>
<%= link_to 'Jauns Pieteikums', new_sudziba_path %> |
<%= link_to 'Klientu saraksts', clients_path %> |
<%= link_to 'Lietotaju saraksts', users_path %> 
<div class="topright"><%= current_user.email %></div>
<table  class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= sortable "id" %></th>
      <th scope="col">Nosaukums</th>
      <th scope="col">Detalas</th>
      <th scope="col"><%= sortable "customer", "Klients" %></th>
      <th scope="col"><%= sortable "user", "Lietotajs" %></th>
      <th scope="col"><%= sortable "status", "Status" %></th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @sudzibas.each do |sudziba| %>
    <tr>
      <td><%= sudziba.id %></td>
      <td><%= sudziba.title %></td>
      <td><%= sudziba.description %></td>
      <td><%= sudziba.customer %></td>
      <td><%= sudziba.user %></td>
      <td><%= sudziba.status %></td>
      <td><%= link_to 'Vairak', sudziba_path(sudziba) %></td>
      <td><%= link_to 'Rediget', edit_sudziba_path(sudziba) %></td>
      <td><%= link_to 'Dzest', sudziba_path(sudziba),method: :delete, data: { confirm: 'Vai jus esat parliecinati?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

name/app/views/sudzibas/new.html.erb
<div class="container">
<div class="topright2"><%= current_user.email %></div>

<h3>Jauns Pieteikums</h3>
<hr />
 
<%= render 'form' %>
 
<%= link_to 'Atcelt', sudzibas_path %>

</div>

name/app/views/sudzibas/show.html.erb
<div class="container">
<div class="topright2"><%= current_user.email %></div>

<h3>Pieteikuma informacija</h3>
<hr />

  <strong>ID:</strong>
  <%= @sudziba.id %> <br>

  <strong>Nosaukums:</strong>
  <%= @sudziba.title %> <br>
 
  <strong>Detalas:</strong>
  <%= @sudziba.description %> <br>

  <strong>Klients:</strong>
  <%= @sudziba.customer %> <br> 

  <strong>Lietotajs:</strong>
  <%= @sudziba.user %> <br>

  <strong>Status:</strong>
  <%= @sudziba.status %> <br>

  <strong>Tika izveidots:</strong>
  <%= @sudziba.created_at %> <br>

<hr />

<h4>Piezimes:</h4>
<%= render @sudziba.piezimes %>
<hr />
<h4>Pievienot piezimi:</h4>
<%= render 'piezimes/form' %>
<hr /> 

<%= link_to 'Rediget', edit_sudziba_path(@sudziba) %> |
<%= link_to 'Atpakal', sudzibas_path %>

</div>

name/app/views/users/index.html.erb
<h3>Lietotaju saraksts</h3>
<%= link_to 'Pieteikumu saraksts', sudzibas_path %> |
<%= link_to 'Klientu saraksts', clients_path %> 
<div class="topright"><%= current_user.email %></div>

<table  class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Vards</th>
      <th scope="col">E-pasts</th>
      <th scope="col" colspan="1"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Dzest', users_path(user), method: :delete, data: { confirm: 'Vai jus esat parliecinati?' } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

name/app/views/users/new.html.erb
<div class="container">
<h3>Pieslegsanas vai Registracija</h3>
<hr/>
<body>
	<h4>
		Pieslegties
	</h4>

	<form action="/sessions" method="POST">
		<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
		<input type="email" name="login[email]" placeholder="e-pasts">
		<input type="password" name="login[password]" placeholder="parole">		
		<input type="submit" name="submit" class="submit">
	</form>

	<div class="errors">
		<% if flash[:login_errors]%>
			<% flash[:login_errors].each do |error|%>
				<p><%=error%></p>
			<%end%>
		<%end%>
	</div>
	<hr/>
	<h4>
		Registreties
	</h4>

	<form action="/users" method="POST">
		<input type="hidden" name="authenticity_token" value="form_authenticity_token">			
		<input type="name" name="user[name]" placeholder="vards">
		<input type="email" name="user[email]" placeholder="e-pasts">
		<input type="password" name="user[password]" placeholder="parole">
		<input type="password" name="user[password_confirmation]" placeholder="paroles apstiprinasana">
		<input type="submit" name="submit" class="submit">
	</form>

	<div class="errors">
		<% if flash[:register_errors]%>
			<% flash[:register_errors].each do |error|%>
				<p><%=error%></p>
			<%end%>
		<%end%>
	</div>


</body>
</div>